config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "departments#index"

  resources :departments do 
  resources :items
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/department.rb
class Department < ApplicationRecord
    has_many :items 
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :department
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
  before_action :set_department, only: [:show, :edit, :update, :destroy]
  def index
    @departments = Department.all
  end

  def show
    #@department = Department.find(params[:id])
  end

  def new
    @department = Department.new
    render partial: "form"
  end

  def edit
    #@department = Department.find(params[:id])
      render partial: "form"
  end

  def create
     @department = Department.new(department_params)
      if @department.save
      redirect_to departments_path
      else render partial: "form"
      end

  end

  def update
    #@department = Department.find(params[:id])
    if @department.update(department_params)
      redirect_to departments_path(@department.id)
    else 
      render partial: "form"
    end 
  end

  def destroy
    #@department = Department.find(params[:id])
    @department.destroy
    redirect_to departments_path

  end 
  
  private
  def department_params
    #params = {departments: { name: "Department Name"}}
    params.require(:department).permit(:name)
   end 
 
   def set_department
    @department = Department.find(params[:id])
   end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]
  before_action :set_department
  
  def index
    @items = @department.items
  end

  def show

  end

  def new
    @item = @department.items.new
    render partial: "form"
  end

  def edit
    render partial: "form"
  end

  def update
    if @item.update(item_params)
      redirect_to [@department, @item]
    else
      render :edit
    end
  end

  def create
    @item = @department.items.new(item_params)

    if @item.save
      redirect_to [@department, @item]
    else
      render :new
    end
  end

  def destroy
    @item.destroy
    redirect_to department_item_path
  end
  private
  def set_item
    @item = Item.find(params[:id])
  end

  def set_department
  @department = Department.find(params[:department_id])
  end

  def item_params
    params.require(:item).permit(:name)
  end

  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/departments/_form.html.erb
<h1><%= @department.id ? "Edit Department" : "Create Department" %></h1>
<hr />
<%= form_for @department do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, required: true, autofocus: true %>
  <br />
<% end %>

app/views/departments/edit.html.erb
<h1>Edit Department</h1>
<hr />
<%= form_for @departments do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, required: true, autofocus: true %>
  <%= f.submit %>
<% end %>

app/views/departments/index.html.erb
<h1> Departments </h1>
<%= link_to "Create Department", new_department_path %>
<br/>
<br/>


<ul>
  <% @departments.each do |department| %>
    <li><strong><%= link_to department.name, department %></strong></li>
<%= link_to "Edit Department", edit_department_path(department.id) %>
<br/>
<%= link_to "Delete Department", department_path(department.id), method: :delete %>
  <% end %>
</ul>

app/views/departments/new.html.erb
<h1>Departments#new</h1>
<p>Find me in app/views/departments/new.html.erb</p>

app/views/departments/show.html.erb
<h1><%= @department.name %></h1>
<hr />
<p>What would you like to do?</p>
<%= link_to 'View Department', department_path(@department) %>
<br />
<%= link_to 'Edit Department', edit_department_path(:id) %>
<br />
<%= link_to 'Delete Department', @department, method: :delete %>
<h1>Items</h1>
<%= link_to 'Ceate a item', new_department_item_path(@department) %>
<ul>
  <% @department.items.each do |item| %>
    <li><%= link_to item.name, [@department, item] %></li>
  <% end %>
</ul>

app/views/items/_form.html.erb
<h1><%= @item.id ? 'Edit Item' : 'Create Item' %></h1>
<hr />
<%= form_for [@department, @item] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, required: true, autofocus: true %>

  <%= f.submit %>
<% end %>

app/views/items/edit.html.erb
<h1>Items#edit</h1>
<p>Find me in app/views/items/edit.html.erb</p>

app/views/items/index.html.erb
<h1>Items</h1>
<%= link_to 'Ceate a item', new_department_item_path(@department) %>
<ul>
  <% @items.each do |item| %>
    <li><%= link_to item.name, [@department, item] %></li>
  <% end %>
</ul>

app/views/items/new.html.erb
<h1>Create a item</h1>
<%= form_for [@department, @item] do |f| %>
  <%= f.label :name %>
  <%= f.text_area :name, required: true %>
  <br />
 
  <%= f.submit %>
<% end %>

app/views/items/show.html.erb
<h1><%= @department.name %> <%= @item.name %></h1>
<%= link_to 'Create Item', new_department_item_path(@department) %>
<%= link_to 'Edit Item', edit_department_item_path(@department, @item) %>
<%= link_to 'Delete Item', [@department, @item], method: :delete %>
<%= link_to 'Back To Item', department_item_path(@department, @item) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DepartmentStore</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>